#!/usr/bin/env python3
"""
G-Code Skill Manager - Main CLI
A tool to manage the .gcode/skills folder for the G-Code agent.
Supports local paths, GitHub Trees, and Hugging Face Spaces.
Automatically maintains a structure.md file for the agent.
"""

import os
import sys
import argparse
import shutil
from github_provider import GitHubProvider
from huggingface_provider import HuggingFaceProvider, BLUE, GREEN, YELLOW, RED, BOLD, RESET, DIM

def get_skills_dir():
    """Determine the skills directory based on the app's structure."""
    app_path = os.path.dirname(os.path.abspath(__file__))
    skills_dir = os.path.join(app_path, ".gcode", "skills")
    return skills_dir

def ensure_skills_dir():
    """Creates the skills directory if it doesn't exist."""
    skills_dir = get_skills_dir()
    if not os.path.exists(skills_dir):
        os.makedirs(skills_dir, exist_ok=True)
        print(f"{GREEN}✔ Created skills directory at: {skills_dir}{RESET}")
    return skills_dir

def update_structure_md():
    """Generates a structure.md file in the skills directory listing all skills and their files."""
    skills_dir = get_skills_dir()
    if not os.path.exists(skills_dir):
        return

    structure_file = os.path.join(skills_dir, "structure.md")
    content = [
        "# G-Code Skills Structure\n",
        "This file is automatically generated and used by the G-Code agent to navigate installed skills.",
        "It provides a map of all available skill directories and their contents.\n"
    ]

    # Get all subdirectories (each is a skill)
    items = sorted([d for d in os.listdir(skills_dir) if os.path.isdir(os.path.join(skills_dir, d)) and not d.startswith('.')])
    
    if not items:
        content.append("No skills currently installed.")
    else:
        for skill in items:
            content.append(f"## 📁 {skill}")
            content.append(f"Root Path: `.gcode/skills/{skill}/`")
            content.append("### File Tree:")
            
            skill_path = os.path.join(skills_dir, skill)
            for root, dirs, files in os.walk(skill_path):
                # Calculate depth for visual indentation
                level = root.replace(skill_path, '').count(os.sep)
                indent = '  ' * (level)
                
                sub_dir = os.path.basename(root)
                if sub_dir != skill:
                    content.append(f"{indent}  📁 {sub_dir}/")
                
                file_indent = '  ' * (level + 1)
                for f in sorted(files):
                    content.append(f"{file_indent}📄 {f}")
            content.append("\n---\n") # Section separator

    with open(structure_file, "w", encoding="utf-8") as f:
        f.write("\n".join(content))
    print(f"{DIM}⚙ Updated structure.md with navigation paths{RESET}")

def add_local_skill(source_path):
    """Copies a local file or directory into the skills directory."""
    skills_dir = ensure_skills_dir()
    if not os.path.exists(source_path):
        print(f"{RED}✘ Error: Source '{source_path}' not found.{RESET}")
        return

    name = os.path.basename(source_path.rstrip(os.sep))
    dest_path = os.path.join(skills_dir, name)
    os.makedirs(skills_dir, exist_ok=True)

    try:
        if os.path.isdir(source_path):
            if os.path.exists(dest_path): shutil.rmtree(dest_path)
            shutil.copytree(source_path, dest_path)
        else:
            os.makedirs(os.path.dirname(dest_path), exist_ok=True)
            shutil.copy2(source_path, dest_path)
        print(f"{GREEN}✔ Added local skill: {BOLD}{name}{RESET}")
        update_structure_md()
    except Exception as e:
        print(f"{RED}✘ Error: {e}{RESET}")

def list_skills(path=None, indent=0):
    """Recursively lists local skills with icons."""
    if path is None:
        path = get_skills_dir()
        if not os.path.exists(path):
            print(f"{YELLOW}No skills directory found.{RESET}")
            return
        print(f"{BLUE}{BOLD}Current G-Code Skills:{RESET}")

    if not os.path.isdir(path):
        return

    items = sorted(os.listdir(path))
    for item in items:
        if item.startswith('.') or item == "structure.md": continue
        full_path = os.path.join(path, item)
        if os.path.isdir(full_path):
            print("  " * indent + f"📁 {item}")
            list_skills(full_path, indent + 1)
        else:
            print("  " * indent + f"📄 {item}")

def remove_skill(name):
    """Removes a skill directory or file."""
    target = os.path.join(get_skills_dir(), name)
    if os.path.exists(target):
        try:
            if os.path.isdir(target): 
                shutil.rmtree(target)
            else: 
                os.remove(target)
            print(f"{GREEN}✔ Removed skill: {name}{RESET}")
            update_structure_md()
        except Exception as e:
            print(f"{RED}✘ Error removing skill: {e}{RESET}")
    else:
        print(f"{RED}✘ Error: Skill '{name}' not found.{RESET}")

def main():
    # Pre-process arguments to handle prefixes like 'npx skills' or 'skills'
    argv = sys.argv[1:]
    while argv and argv[0] in ['npx', 'skills']:
        argv = argv[1:]

    parser = argparse.ArgumentParser(description="G-Code Skill Manager")
    subparsers = parser.add_subparsers(dest="command")

    # Add command
    add_p = subparsers.add_parser("add", help="Add skill (Local Path, GitHub URL, or HF Space URL)")
    add_p.add_argument("source", help="Path or URL (GitHub/HuggingFace)")
    add_p.add_argument("--skill", help="Specific skill name/path within the repository or space")

    # List command
    subparsers.add_parser("ls", help="List all installed skills")
    
    # Remove command
    rm_p = subparsers.add_parser("rm", help="Remove an installed skill")
    rm_p.add_argument("name", help="Skill name (folder name)")

    args = parser.parse_args(argv)

    if args.command == "add":
        source = args.source
        skills_dir = get_skills_dir()
        
        if source.startswith(("http://", "https://")):
            success = False
            if "huggingface.co" in source:
                success = HuggingFaceProvider().install_skill(source, skills_dir)
            elif "github.com" in source:
                if args.skill and "/tree/" not in source and "/blob/" not in source:
                    source = f"{source.rstrip('/')}/tree/main/{args.skill}"
                success = GitHubProvider().install_skill(source, skills_dir)
            
            if success:
                update_structure_md()
        else:
            add_local_skill(source)
            
    elif args.command == "ls":
        list_skills()
    elif args.command == "rm":
        remove_skill(args.name)
    else:
        parser.print_help()

if __name__ == "__main__":
    main()